// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpgEcZuvQW70JHFbJ2mBHlM_hf8DsPWvQ',
    appId: '1:244660030535:web:ee21e126b63aa82c843562',
    messagingSenderId: '244660030535',
    projectId: 'printing-commerce',
    authDomain: 'printing-commerce.firebaseapp.com',
    storageBucket: 'printing-commerce.appspot.com',
    databaseURL: 'https://printing-commerce-default-rtdb.firebaseio.com',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRJhzurQvYTg2YGw5kyQ6ECl-Zmt1z9tI',
    appId: '1:244660030535:android:d53cf1648197ffc5843562',
    messagingSenderId: '244660030535',
    projectId: 'printing-commerce',
    storageBucket: 'printing-commerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjSYe8ggBEbcZ4AjmmSH3M6QtyFDOYv7A',
    appId: '1:244660030535:ios:c85cb463df397eff843562',
    messagingSenderId: '244660030535',
    projectId: 'printing-commerce',
    storageBucket: 'printing-commerce.firebasestorage.app',
    iosBundleId: 'com.example.tataapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjSYe8ggBEbcZ4AjmmSH3M6QtyFDOYv7A',
    appId: '1:244660030535:ios:c85cb463df397eff843562',
    messagingSenderId: '244660030535',
    projectId: 'printing-commerce',
    storageBucket: 'printing-commerce.firebasestorage.app',
    iosBundleId: 'com.example.tataapps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpgEcZuvQW70JHFbJ2mBHlM_hf8DsPWvQ',
    appId: '1:244660030535:web:3340b70f50c4fbd9843562',
    messagingSenderId: '244660030535',
    projectId: 'printing-commerce',
    authDomain: 'printing-commerce.firebaseapp.com',
    storageBucket: 'printing-commerce.firebasestorage.app',
  );
}
